### ISSUE TITLE
Bug report: round_sig(x, sig) not rounding correctly for some (even possibly) numbers ending with 5

### ISSUE THREAD

**Issue by akshatpoddar** [open-resources/problem_bank_helpers#1]
The function round_sig(x, sig) is not rounding some numbers correctly when they have 5 as the last digit. This is due to the rounding half to even principle that the sigfig.round() function uses. The round_sig() function calls a wrapper function in problem_bank_helpers module called roundp() which in turn calls the sigfig.round() function which is the probable cause of this bug.

To reproduce: 

```
pbh.round_sig(25,1)
pbh.round_sig(45,1)
pbh.round_sig(85,1)
pbh.round_sig(4.675, 3)
```

Generated Output: 
20
40
80
4.67

Desired Output:
30
50
90
4.68

Tests that fail due to this bug:
```
test_round_sig_numbers_ending_with_n() # for n=5
test_round_sig_edge_cases()
```

**Comment by amurph24** [comment]
Looks to be due to passing floats through to the `round()` function, solved by passing decimals into `round()` then casting to floats at the end.
